jobber_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.register,name='register'),
    path('accounts/profile/',views.profile, name = 'profile'),
    path('accounts/profile/<int:user_id>/', views.public_profile, name='public_profile'),
    path('about/', views.about, name='about'),
    path('search/',views.search, name = 'search'),
    path('events/<int:event_id>/', views.event_detail, name='detail'),
    path('events/<int:event_id>/edit/', views.event_edit, name='edit'),
    path('events/<int:event_id>/delete/', views.event_delete, name='delete'),
    path('events/<int:event_id>/add_registration/', views.add_registration, name='add_registration'),
    path('events/<int:event_id>/remove_registration/', views.remove_registration, name='remove_registration'),
    path('events/add_event/', views.add_event, name='add_event'),
    
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
FOCUS = (
    ('T', 'Tech'),
    ('M', 'Marketing'),
    ('C', 'Content Creation')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    bio = models.TextField()

    

    def __str__(self):
        return f'{self.user.username}\'s Profile '

class Event(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    time = models.CharField(max_length=25)
    speakers = models.CharField(max_length=250)
    focus = models.CharField(
        max_length=1,
        choices=FOCUS,
        default=FOCUS[0][0]
    )
    description = models.TextField()
    url = models.CharField(
        max_length=250,
        default='https://us05web.zoom.us/j/7915630422?pwd=Q2hnV2NnUEdFVTNYNUJRTWtHdDlzZz09'
        )
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.title

main_app/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Event

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']

# this form is used to update the content of the field of username and email of the login user
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','email', 'first_name', 'last_name']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['bio']

class EventForm(forms.ModelForm):
    class Meta:
        model=Event
        fields=['title', 'date', 'time', 'speakers', 'focus', 'description', 'users']

main_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfileUpdateForm, EventForm
from .models import Profile, Event, User
from django.contrib import messages

# Home View
def home(request):
    events = Event.objects.all().order_by('date')
    return render(request, 'home.html', { 'events': events })

# Register of the user
def register(request):
    error_message = ''
    if request.method == "POST":
    # registerform is made in the form.py file and response with post method
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f'New account Created: {username}')
            profile = Profile(user = user, bio = '' )
            profile.save()
            username = form.cleaned_data.get('username')
            
            messages.success(request, f'New Account Created: {username}')
            login(request, user)
            messages.success(request, f'you are now logged in as: {username}')
            return redirect('profile')
    else:
        form = RegisterForm()
        error_message = 'Invalid sign up - try again'
        
        return render(request, 'registration/register.html',{ 'form': form })
        # for msg in form.error_messages:
        #     messages.error(request, form.error_messages[msg])
            
    return render(request, "registration/register.html",{'form' : form, 'message': error_message})

# after logging in they will land on profile by default.
@login_required
def profile(request):
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, instance = request.user.profile)
        u_form = UserUpdateForm(request.POST,instance=request.user)
        if p_form.is_valid() and u_form.is_valid():
            
             u_form.save()
             p_form.save()
             messages.success(request, 'You are logged in successfully')
             return redirect('profile')
    else:
       
        profile = Profile.objects.get(user_id=request.user.id)
        p_form = ProfileUpdateForm(instance=profile)
        
        u_form = UserUpdateForm(instance = request.user)

    events = Event.objects.filter(users=request.user)
    context={'p_form': p_form, 'u_form': u_form, 'events': events}
     
    return render(request, 'profile.html',context)

# Public Profile
def public_profile(request, user_id):
    user = User.objects.get(id=user_id)
    events = Event.objects.filter(users=user)
    return render(request, 'public.html', { 'user': user, 'events': events })

# About View
def about(request):
    return render(request, 'about.html')

# Event Details
def event_detail(request, event_id):
    event = Event.objects.get(id=event_id)
    total_registered = len(event.users.all())
    registered = False
    if request.user:
        if request.user in event.users.all():
            registered = True
    context = {
        'event': event,
        'registered': registered,
        'total_registered': total_registered
    }
    return render(request, 'events/detail.html', context)
            

# Register user for event
@login_required
def add_registration(request, event_id):
    event = Event.objects.get(id=event_id)
    if request.user in event.users.all():
        messages.error(request, 'Event is already added')
    else:
        event.users.add(request.user)
        messages.success(request, 'Event has been added')
    return redirect('profile')

# Unregister user for event
@login_required
def remove_registration(request, event_id):
    event = Event.objects.get(id=event_id)
    x = event.users.all()
    for X in x:
        if X == request.user:
            event.users.remove(request.user.id)
            return render(request, 'landing.html', {'message': "You sure you want to delete all those things"})
            messages.success(request, 'not deleted')
        else:      
            messages.error(request, 'deleted')  
    if request.method == 'POST':
        event.users.remove(request.user.id)
    
    return redirect('profile')
    
# search
def search(request):
    # this is the query that we access from the url which is send from the search form
    query1 = request.GET['query']
    query2 = request.GET['option']
    
    # In this way we can use __icontains module to  set any attribute as query.
    events = Event.objects.filter(title__icontains = query1, focus__icontains = query2) 

    if(events):
        messages.success(request,'this is the result')
        return render(request, 'search.html',{'events': events})

    elif(not events):
        messages.error(request, 'There is no such Event')
        return redirect('home')

    return redirect('search')

# SuperUser Add Event
@login_required
def add_event(request):
    form = EventForm(request.POST or None)
    if request.POST and form.is_valid():
        new_event = form.save(commit=False)
        new_event.save()
        return redirect('home')
    else:
        return render(request, 'events/new.html', { 'form': form })

# Edit Event
@login_required
def event_edit(request, event_id):
    event = Event.objects.get(id=event_id)
    event_form = EventForm(request.POST or None, instance=event)
    if request.POST and event_form.is_valid():
        event_form.save()
        return redirect('detail', event_id=event_id)
    else:
        return render(request, 'events/edit.html', { 'event': event, 'event_form': event_form })

# Delete Event
@login_required
def event_delete(request, event_id):
    Event.objects.get(id=event_id).delete()
    return redirect('home')

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h2 class="label">About Jobber</h2>
<hr />

<div class="about">
    <div class="row">
        <div class="col l3 s12">
            <h4 class="about-head">Why Jobber?</h4>
            <p>Jobber is a public, easy to use recruiting events site. We pride ourselves on giving our users the means to find the job of their dreams. With our user friendly design, checkout events happening in the area and sign up to register to attend. You can unregister at anytime and keep track of all your events on your personal profile page.</p>
        </div>
        <div class="col l3 s12">
            <h4 class="about-head">Our Mission</h4>
            <p>Our mission here at Jobber is to provide our users with easy access to recruitment opportunities. We know the world is rough right now, so we want to make it easy. Search for events or industry specifics, join any event that catches your attention, and keep track of those you've signed up for and attended. Jobber is here to make your life easier</p>
        </div>
        <div class="col l3 s12">
            <h4 class="about-head">Our Team</h4>
            <p>Here at Jobber, our team is working tirelessly to put together the events and website that will make your job search a breeze. Our team is always working on ways to improve our site and always looking for new events to add for our users. We strive for user-friendly interactions and on keeping your information safe.</p>
        </div>
        <div class="col l3 s12">
            <h4 class="about-head">COVID-19</h4>
            <p>Due to the circumstanced brought on by COVID-19, all Jobber events have been moved to virtual events indefinitely. When registering for an event, the video link will be made available on the event's page. We advise against any in person recruitment events at this time. Any exceptions will be made clear on the event's page.</p>
        </div>
    </div> 
</div>

{% endblock  %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Jobber</title>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Permanent+Marker&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper blue">
     
        <ul>
          <li><a href="/" id="logo" class="left brand-logo">&nbsp;&nbsp;Jobber</a></li>
        </ul>

        <a href="#" data-target="mobile-menu" class="right sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="/about">About</a></li>

          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <li><a href="{% url 'add_event' %}">Add Event</a></li>
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
              {% else %}
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% endif %}
          {% else %}
            <li><a href="{% url 'register' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
             
        </ul>
      </div>
    </nav>

        <ul class="sidenav" id="mobile-menu">
          <li><a href="/about">About</a></li>

          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <li><a href="{% url 'add_event' %}">Add Event</a></li>
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
              {% else %}
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% endif %}
          {% else %}
            <li><a href="{% url 'register' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>

      <script>
        document.addEventListener('DOMContentLoaded', function() {
        let elems = document.querySelectorAll('.sidenav');
        let instances = M.Sidenav.init(elems, {});
        });
      </script>
   
    {% if messages %}
      {%for message in messages %}
          {% if message.tags == 'success' %}
          
              <script>M.toast({html: "{{message}}", classes:'green rounded', displayLength:2000});</script>

          {% elif message.tags == 'info'%}

               <script>M.toast({html: "{{message}}", classes:'blue rounded', displayLength:2000});</script>

          {% elif message.tags == 'error'%}

               <script>M.toast({html: "{{message}}", classes:'red rounded', displayLength:2000});</script>

          {% endif %}
           
      {% endfor %}
      {% endif %}
  </header>

  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer blue">
    <div class="right">All Rights Reserved, &copy; 2021 Jobber &nbsp;</div>
  </footer>

  
</body>
</html>

main_app/templates/events/detail.html
{% extends 'base.html' %}
{% block content %}

<h3 class="label">{{ event.title }}</h3>

<div class="detail">
    {% if user.is_superuser %}
    <p>Total Registered: {{ total_registered }}</p>
    {% endif %}

    <p>Date: {{ event.date }}</p>
    <p>Time: {{ event.time }}</p>

    <p>Industry Focus: {{ event.get_focus_display }}</p>
    <p>Speaker(s): {{ event.speakers }}</p>

    <p>Description: {{ event.description }}</p>

    <div class="registration">
        {% if user.is_authenticated %}
            {% if registered %}
                <form action="{% url 'remove_registration' event.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn blue darken-2"id="unregister" value="Unregister">
                </form>

            {% else %}
        <hr>
                <form action="{% url 'add_registration' event.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn blue darken-2"id="register" value="Register">
                </form> 
            {% endif %}
        {% else %}
        <bold> Please Log In to Register for this Event <bold>
        {% endif %}
    </div> 
</div>

{% if user.is_superuser %}

<hr />
<form action="{% url 'edit' event.id %}" method="GET">
    <input type="submit" class="btn blue darken-2" value="Edit">
</form>
<hr />
<form action="{% url 'delete' event.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn blue darken-2" value="Delete">
</form>

{% endif %}

{% endblock %}

main_app/templates/events/edit.html
{% extends 'base.html' %}
{% block content %}

<h2 class="admin-header">Editing Event: {{ event.title }}</h2>

<form action="{% url 'edit' event.id %}" method="POST">
    {% csrf_token %}
    {{ event_form.as_p }}
    <input type="submit" class="btn blue darken-2" value="Edit Event">
</form>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoclose: true
    });

    const focusEl = document.getElementById('id_focus');
    M.FormSelect.init(focusEl);

    const userEl = document.getElementById('id_users');
    M.FormSelect.init(userEl);
</script>

{% endblock  %}

main_app/templates/events/new.html
{% extends 'base.html' %}
{% block content %}

<h2 class="admin-header">Add An Event</h2>

<form action="{% url 'add_event' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn blue darken-2" value="Add Event">
</form>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoclose: true
    });

    const focusEl = document.getElementById('id_focus');
    M.FormSelect.init(focusEl);

    const userEl = document.getElementById('id_users');
    M.FormSelect.init(userEl);

</script>

{% endblock  %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div class="col l4 s 12">
        <h3 class="slogan">Recruitment Redefined</h3>
        <h5 class="subslogan">We have the right position for you, guaranteed</h5>
    </div>
    <div class="col l8 s12">
        <img src="https://i.imgur.com/8I7pftrl.jpg" alt="jobber-home">
    </div>
</div>
<hr />
  
    <form action="/search" method="get">
        <input type="search" name="query" id="query">
            <select class="browser-default" name="option">
            <option value="T" selected=selected>Tech</option>
            <option value="M">Marketing</option>
            <option value="C">Content-Creation</option>
            </select>
        <input type="submit" class="btn blue darken-2" value="Search">
    </form>

<h4>Upcoming Events</h4>
<div class="events">
    <div class="row">
        {% for event in events %}
            <div class="col l3 m6">
                <div class="card small z-depth-3">
                    <a href="{% url 'detail' event.id %}">
                        <div class="card-content black-text">
                            <span class="card-title">{{ event.title }}</span>
                            <p>{{ event.description|truncatechars:80 }}</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/landing.html
{% extends 'base.html' %}
{% block content %}

<h2>The Event has been deleted! successfully.</h2>


<script>
    alert('{{ message }}');
</script>
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% block content %}

{% if user.is_authenticated %}

<h2 class="welcome">Welcome , {{ user.get_username }}</h1>
<p>Email: {{user.email}}</p>
<p>Bio: {{user.profile.bio}}</p>

<hr />

<p>Edit Profile Information Below:</p>
<form method='POST' enctype="multipart/form-data">
    {%csrf_token%}
    {{u_form.as_p}}
    {{p_form.as_p}}
    <input type="submit" class="btn blue darken-2" value="Update">
</form>
<hr />

{% endif %}

<h5>Your Meetings</h5>
<div class="row">
    {% if events %}
        {% for event in events %}
            <div class="col l3 m6">
                <div class="card medium z-depth-3"> 
                    <a href="{% url 'detail' event.id %}">
                        <div class="card-content">
                            <span class="card-title black-text">{{ event.title }}</span>
                            <p class="black-text">{{ event.description|truncatechars:80 }}</p>
                            <div class="card-action center-align"><a href="{{ event.url }}">Click Here to Open Event</a></div>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h4>No Registered Events</h4>
    {% endif %}
</div>


{% endblock %}

main_app/templates/public.html
{% extends 'base.html' %}
{% block content %}

<div class="public">
    <h2>{{ user.username }}'s Profile</h2>
    <h5>Email: {{ user.email }}</h5>
    <h5>Date Joined: {{ user.date_joined|truncatechars:10 }}</h5>
    <hr />
    <h5>{{ user.username }}'s Upcoming Meetings</h5>
    <div class="row">
        {% if events %}
            {% for event in events %}
                <div class="col l3 m6">
                    <div class="card medium"> 
                        <a href="{% url 'detail' event.id %}">
                            <div class="card-content">
                                <span class="card-title black-text">{{ event.title }}</span>
                                <p class="black-text">{{ event.description|truncatechars:80 }}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4>No Registered Events</h4>
        {% endif %}
    </div>
</div>

{% endblock  %}

main_app/templates/search.html
{% extends 'base.html' %}
{% block content %}

    

 
<h2>Search Results:</h2>
{% comment %} it will help us to display the message. events itself is a disctionary if it is none then following message will show {% endcomment %}
{%if events|length < 1 %}
{% comment %} querry is carried over here through the params that we define in the views of search {% endcomment %}
<p>Your search <b>{{query}}</b> did not match. Try again</p>
{% endif %}



<div class="row">
    {% for event in events %}
        <div class="col l3 m6">
            <div class="card small z-depth-3">
            <a href="{% url 'detail' event.id %}">
                <div class="card-content black-text">
                    <span class="card-title">{{ event.title }}</span>
                    <p>{{ event.description|truncatechars:80 }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}